// GENERATED by scripts/gen-stats.mjs — do not edit by hand.
// The collected vitest test total (includes parametrised / loop-generated cases
// a static scan can't see). Refreshed on `predev:build` and `pnpm stats`.
export const FOLD_TEST_COUNT = 735;
