// Regenerates demo/shell/gallery-stats.generated.ts — the one gallery stat that
// can't be counted live in the browser: the collected vitest test total.
//
// `vitest list` COLLECTS every test (evaluating the spec files, so parametrised
// / loop-generated cases are included) without running their bodies — the exact
// number, cheaply. Theme + component counts stay live in gallery-stats.ts (Vite
// globs), so this script owns only the test count.
//
// Wired to `predev:build` (the deployed gallery is always fresh) and `pnpm stats`.
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "demo/shell/gallery-stats.generated.ts");

const raw = execFileSync("npx", ["vitest", "list"], {
  cwd: root,
  encoding: "utf8",
  stdio: ["ignore", "pipe", "ignore"],
});
const testCount = raw
  .split("\n")
  .filter((line) => line.trim().length > 0).length;

if (!Number.isInteger(testCount) || testCount <= 0) {
  throw new Error(`gen-stats: implausible test count ${testCount}`);
}

const body = `// GENERATED by scripts/gen-stats.mjs — do not edit by hand.
// The collected vitest test total (includes parametrised / loop-generated cases
// a static scan can't see). Refreshed on \`predev:build\` and \`pnpm stats\`.
export const FOLD_TEST_COUNT = ${testCount};
`;
writeFileSync(out, body);
console.log(`gen-stats: FOLD_TEST_COUNT = ${testCount} → ${out}`);
